export { HomeInstitutional } from "./HomeInstitutional";
export { CTASection } from "./CTASection";
export { EventCard } from "./EventCard";
export { HeroInstitutional } from "./HeroInstitutional";
export { InstitutionalCard } from "./InstitutionalCard";
export { InstitutionalFooter } from "./InstitutionalFooter";
export { InstitutionalGallery } from "./InstitutionalGallery";
export { NavbarPremium, type NavLinkItem } from "./NavbarPremium";
export { NewsCard } from "./NewsCard";
export { ProgramCard } from "./ProgramCard";
export { SectionTitle } from "./SectionTitle";
export { StatsInstitution } from "./StatsInstitution";
export { TeacherCard } from "./TeacherCard";
export { TestimonialCard } from "./TestimonialCard";
export { VerseBlock } from "./VerseBlock";
