/**
 * OT-BRANDING-005 — Especificaciones del catálogo visual
 * @see docs/design/COMPONENTS.md
 */

export interface ComponentSpec {
  id: string;
  name: string;
  whenToUse: string;
  variants?: string[];
  sizes?: string[];
  states?: string[];
  tokens: string[];
  accessibility: string[];
  props: string[];
  example: string;
  source: string;
}

export const componentSpecs: ComponentSpec[] = [
  {
    id: "button",
    name: "Button",
    whenToUse: "Acciones primarias, secundarias y navegación con apariencia de botón.",
    variants: ["primary", "secondary", "outline", "ghost", "danger", "success"],
    sizes: ["sm", "md", "lg"],
    states: ["default", "hover", "active", "disabled", "loading"],
    tokens: ["--primary", "--secondary", "--accent", "--success", "--radius-md", "--transition-fast"],
    accessibility: ["focus-ring", "disabled nativo", "Loader2 aria-hidden en loading"],
    props: ["variant?", "size?", "loading?", "disabled?", "href?", "onClick", "children"],
    example: `<Button variant="primary" size="md">Guardar</Button>`,
    source: "src/components/ui/button.tsx",
  },
  {
    id: "badge",
    name: "Badge",
    whenToUse: "Estados compactos, etiquetas y contadores en listas y workflows.",
    variants: ["success", "warning", "error", "info", "neutral"],
    states: ["static"],
    tokens: ["--success", "--accent", "--light", "--background-muted", "--border"],
    accessibility: ["Texto legible dentro del badge; no usar solo color"],
    props: ["variant?", "className?", "children"],
    example: `<Badge variant="info">En revisión</Badge>`,
    source: "src/components/ui/badge.tsx",
  },
  {
    id: "card",
    name: "Card",
    whenToUse: "Agrupar contenido en dashboards, configuración y portal.",
    variants: ["default", "outlined", "elevated", "interactive"],
    states: ["default", "hover (interactive)"],
    tokens: ["--border", "--background", "--shadow-sm", "--shadow-md", "--radius-lg"],
    accessibility: ["interactive: cursor + foco en elemento clicable padre"],
    props: ["variant?", "CardHeader", "CardTitle", "CardDescription", "CardContent", "CardFooter"],
    example: `<Card variant="elevated"><CardHeader><CardTitle>Título</CardTitle></CardHeader></Card>`,
    source: "src/components/ui/card.tsx",
  },
  {
    id: "input",
    name: "Input",
    whenToUse: "Campos de texto en formularios CMS y portal.",
    states: ["default", "focus", "error", "disabled", "loading"],
    tokens: ["--border", "--secondary", "--focus-ring", "--color-danger", "--muted"],
    accessibility: ["label asociado", "error visible", "aria-invalid cuando error"],
    props: ["label?", "error?", "helper?", "icon?", "loading?", "..."],
    example: `<Input label="Email" placeholder="nombre@sem.edu" />`,
    source: "src/components/ui/input.tsx",
  },
  {
    id: "select",
    name: "Select",
    whenToUse: "Selección única en listas cerradas.",
    states: ["default", "focus", "disabled"],
    tokens: ["--border", "--background", "--muted"],
    accessibility: ["label + select nativo o custom con aria"],
    props: ["label?", "options", "placeholder?", "value", "onChange"],
    example: `<Select label="Programa" options={[{ value: "a", label: "A" }]} />`,
    source: "src/components/ui/select.tsx",
  },
  {
    id: "switch",
    name: "Switch",
    whenToUse: "Toggle de configuración on/off.",
    states: ["on", "off", "disabled"],
    tokens: ["--primary", "--accent", "--border"],
    accessibility: ["label clickeable", "role switch", "keyboard Space"],
    props: ["label?", "description?", "checked", "onChange", "disabled?"],
    example: `<Switch label="Activo" checked={on} onChange={setOn} />`,
    source: "src/components/ui/switch.tsx",
  },
  {
    id: "modal",
    name: "Modal",
    whenToUse: "Diálogos de confirmación y formularios cortos.",
    states: ["open", "closed"],
    tokens: ["--background", "--shadow-lg", "--z-modal"],
    accessibility: ["dialog nativo", "Escape cierra", "foco atrapado"],
    props: ["open", "onClose", "title", "description?", "children"],
    example: `<Modal open={open} onClose={close} title="Confirmar">...</Modal>`,
    source: "src/components/ui/modal.tsx",
  },
  {
    id: "drawer",
    name: "Drawer",
    whenToUse: "Panel lateral para edición o navegación secundaria.",
    states: ["open", "closed"],
    tokens: ["--background", "--border", "--z-drawer"],
    accessibility: ["Escape cierra", "título accesible"],
    props: ["open", "onClose", "title", "children"],
    example: `<Drawer open={open} onClose={close} title="Editar">...</Drawer>`,
    source: "src/components/ui/drawer.tsx",
  },
  {
    id: "tabs",
    name: "Tabs",
    whenToUse: "Alternar contenido en el mismo contexto sin cambiar de ruta.",
    states: ["tab activo", "tab inactivo"],
    tokens: ["--border", "--primary", "--background-muted"],
    accessibility: ["tablist / tab / tabpanel", "foco en triggers"],
    props: ["Tabs", "TabsList", "TabsTrigger", "TabsContent", "defaultValue"],
    example: `<Tabs defaultValue="a"><TabsList>...</TabsList></Tabs>`,
    source: "src/components/ui/tabs.tsx",
  },
  {
    id: "alert",
    name: "Alert / Toast",
    whenToUse: "Mensajes de feedback; patrón toast hasta v1.1 con role=status.",
    variants: ["info", "success", "warning", "error"],
    states: ["static"],
    tokens: ["--state-info-*", "--state-success-*", "--state-warning-*", "--state-danger-*"],
    accessibility: ["role=alert o status según urgencia", "título + descripción"],
    props: ["variant", "title?", "children"],
    example: `<Alert variant="success" title="Guardado">Operación exitosa.</Alert>`,
    source: "src/components/ui/alert.tsx",
  },
  {
    id: "cta",
    name: "CTA",
    whenToUse: "Bloques de conversión con título y acciones.",
    variants: ["primary", "accent", "muted"],
    tokens: ["--primary", "--accent", "--background"],
    accessibility: ["jerarquía de headings", "links y botones con texto descriptivo"],
    props: ["title", "description?", "primaryLabel", "primaryHref", "secondaryLabel?", "variant?"],
    example: `<CTA title="¿Listo?" primaryLabel="Empezar" primaryHref="/admision" />`,
    source: "src/components/ui/cta.tsx",
  },
  {
    id: "hero",
    name: "Hero",
    whenToUse: "Cabecera de página con título, descripción y CTAs.",
    tokens: ["--primary", "--accent", "tipografía display"],
    accessibility: ["h1 único por página", "CTAs con texto claro"],
    props: ["title", "subtitle?", "description?", "primaryCta?", "secondaryCta?", "align?"],
    example: `<Hero title="Título" primaryCta={{ label: "Ver", href: "/" }} />`,
    source: "src/components/ui/hero.tsx",
  },
  {
    id: "footer",
    name: "Footer",
    whenToUse: "Pie institucional del portal con columnas de enlaces.",
    tokens: ["--primary", "--gray-*", "--border"],
    accessibility: ["nav con landmarks", "links descriptivos"],
    props: ["columns", "copyright?", "social?"],
    example: `<Footer columns={[...]} copyright="© SEM" />`,
    source: "src/components/ui/footer.tsx",
  },
  {
    id: "empty-state",
    name: "Empty State",
    whenToUse: "Listados o secciones sin contenido disponible.",
    states: ["default"],
    tokens: ["--border", "--background-soft", "--muted", "--radius-xl"],
    accessibility: ["h3 semántico", "acción opcional con Button"],
    props: ["title?", "description?", "actionLabel?", "actionHref?"],
    example: `<PortalEmptyState title="Sin datos" actionLabel="Crear" actionHref="/admin" />`,
    source: "src/components/portal/PortalEmptyState.tsx",
  },
  {
    id: "skeleton",
    name: "Skeleton",
    whenToUse: "Placeholder de carga de contenido.",
    variants: ["text", "rectangular"],
    tokens: ["--background-muted", "animate-pulse"],
    accessibility: ["aria-busy en contenedor padre", "no reemplazar spinner en acciones"],
    props: ["variant?", "className?"],
    example: `<Skeleton variant="text" /><Skeleton className="h-20" />`,
    source: "src/components/ui/skeleton.tsx",
  },
  {
    id: "spinner",
    name: "Spinner / Loader",
    whenToUse: "Indicar acción en curso (submit, fetch).",
    sizes: ["sm", "md", "lg"],
    tokens: ["--muted", "animate-spin"],
    accessibility: ["aria-label Cargando o texto visible junto"],
    props: ["size?"],
    example: `<Spinner size="md" />`,
    source: "src/components/ui/spinner.tsx",
  },
  {
    id: "table",
    name: "Table",
    whenToUse: "Datos tabulares en admin y listados CMS. Patrón HTML con tokens hasta componente Table formal en v1.1.",
    variants: ["default", "striped (hover row)"],
    states: ["default", "hover (row)", "responsive scroll"],
    tokens: ["--border", "--background-muted", "--background-soft", "--foreground", "--muted"],
    accessibility: ["th con scope", "caption opcional", "scroll horizontal con overflow-x-auto"],
    props: ["thead", "tbody", "th", "td", "Badge/Button en celdas"],
    example: `<div className="overflow-x-auto rounded-lg border border-border"><table className="w-full text-sm">...</table></div>`,
    source: "Patrón v1.0 — ver docs/design/COMPONENTS.md#table-patrón-v10",
  },
  {
    id: "timeline",
    name: "Timeline",
    whenToUse: "Procesos, cronología académica, pasos de admisión.",
    variants: ["process", "calendar", "chronology"],
    states: ["pending", "active", "completed", "upcoming"],
    tokens: ["--timeline-accent", "--secondary", "--border", "--transition-normal"],
    accessibility: ["ol con aria-label", "estados no solo por color"],
    props: ["settings", "items", "id?", "muted?"],
    example: `<PortalTimeline settings={{ layout: "auto" }} items={items} />`,
    source: "src/components/portal/experience/timeline/PortalTimeline.tsx",
  },
];

export function getComponentSpec(id: string): ComponentSpec | undefined {
  return componentSpecs.find((s) => s.id === id);
}
