import type { BlockDefinition, BlockType, CmsTemplate, PageBlock } from "@/types/page";
import { createBlockId } from "@/lib/cms/page-utils";
import { blockTypeToDefaultQuery } from "@/lib/content/block-query-defaults";
import { DEFAULT_SEM_PREMIUM_HERO } from "@/lib/portal/hero-defaults";

export const DEFAULT_NAV_LINKS = [
  { label: "Inicio", href: "/" },
  { label: "Programas", href: "/programas" },
  { label: "Admisión", href: "/admision" },
  { label: "Biblioteca", href: "/biblioteca" },
  { label: "Noticias", href: "/noticias" },
  { label: "Contacto", href: "/contacto" },
] as const;

export const DEFAULT_BLOCK_DEFINITIONS: BlockDefinition[] = [
  { _id: "hero", name: "Hero Institucional", component: "HeroInstitutional", category: "Portada", enabled: true },
  { _id: "text", name: "Texto", component: "TextSection", category: "Contenido", enabled: true },
  { _id: "presentation", name: "Presentación", component: "InstitutionPresentation", category: "Contenido", enabled: true },
  { _id: "feature_grid", name: "Feature Grid", component: "PortalFeatureGrid", category: "Experiencia", enabled: true },
  { _id: "audience_profiles", name: "Perfil postulante", component: "AudienceProfilesSection", category: "Conversión", enabled: true },
  { _id: "modality", name: "Modalidad", component: "ModalitySection", category: "Contenido", enabled: true },
  { _id: "programs", name: "Programas", component: "ProgramsGrid", category: "Académico", enabled: true },
  { _id: "academic_offer", name: "Oferta Académica", component: "PortalProgramsSection", category: "Académico", enabled: true },
  { _id: "seminarios_home", name: "Seminarios Home", component: "SeminariosHomeSection", category: "Académico", enabled: true },
  { _id: "teachers", name: "Equipo (legacy)", component: "TeachersGrid", category: "Académico", enabled: true },
  { _id: "people", name: "People Grid", component: "PortalPeopleGrid", category: "Experiencia", enabled: true },
  { _id: "news", name: "News Grid", component: "PortalNewsGrid", category: "Experiencia", enabled: true },
  { _id: "events", name: "Eventos", component: "EventsGrid", category: "Contenido", enabled: true },
  { _id: "academic_agenda", name: "Agenda Académica", component: "AcademicAgendaGrid", category: "Académico", enabled: true },
  { _id: "institutional_notices", name: "Avisos Institucionales", component: "InstitutionalNoticesGrid", category: "Contenido", enabled: true },
  { _id: "library", name: "Biblioteca", component: "LibraryGrid", category: "Académico", enabled: true },
  { _id: "resources", name: "Recursos destacados", component: "ResourcesGrid", category: "Académico", enabled: true },
  { _id: "cta", name: "CTA (legacy)", component: "CTASection", category: "Conversión", enabled: true },
  { _id: "cta_premium", name: "CTA Premium", component: "PortalCTAPremium", category: "Experiencia", enabled: true },
  { _id: "admission_process", name: "Proceso de admisión", component: "AdmissionProcessSection", category: "Conversión", enabled: true },
  { _id: "timeline", name: "Timeline", component: "PortalTimeline", category: "Experiencia", enabled: true },
  { _id: "scholarships", name: "Becas y beneficios", component: "ScholarshipsSection", category: "Conversión", enabled: true },
  { _id: "faq", name: "Preguntas frecuentes", component: "FaqSection", category: "Conversión", enabled: true },
  { _id: "quick_contact", name: "Contacto rápido", component: "QuickContactSection", category: "Conversión", enabled: true },
  { _id: "contact_hub", name: "Contact Hub", component: "PortalContactHub", category: "Experiencia", enabled: true },
  { _id: "experience_form", name: "Experience Form", component: "PortalExperienceForm", category: "Experiencia", enabled: true },
  { _id: "footer_premium", name: "Footer Premium", component: "PortalFooterPremium", category: "Layout", enabled: true },
  { _id: "alliance", name: "Alianza institucional", component: "AllianceSection", category: "Contenido", enabled: true },
  { _id: "testimonials", name: "Testimonios", component: "Testimonials", category: "Contenido", enabled: true },
  { _id: "gallery", name: "Galería", component: "InstitutionGallery", category: "Medios", enabled: true },
  { _id: "stats", name: "Estadísticas", component: "StatsInstitution", category: "Contenido", enabled: true },
  { _id: "video", name: "Video", component: "VideoSection", category: "Medios", enabled: true },
  { _id: "verse", name: "Versículo", component: "VerseBlock", category: "Contenido", enabled: true },
  { _id: "contact", name: "Formulario", component: "ContactForm", category: "Conversión", enabled: true },
  { _id: "divider", name: "Separador", component: "Divider", category: "Layout", enabled: true },
  { _id: "html", name: "HTML", component: "HtmlBlock", category: "Avanzado", enabled: true, adminOnly: true },
  { _id: "markdown", name: "Markdown", component: "MarkdownBlock", category: "Avanzado", enabled: true, adminOnly: true },
];

export const DEFAULT_SETTINGS: Record<BlockType, Record<string, unknown>> = {
  hero: {
    ...DEFAULT_SEM_PREMIUM_HERO,
    institutionName: "",
    motto: "",
    badge: "",
    ctaLabel: "Conoce nuestros programas",
    ctaHref: "/programas",
    primaryLabel: "Postular ahora",
    primaryHref: "/admision",
    secondaryLabel: "Ver programas",
    secondaryHref: "/programas",
    overlayOpacity: 75,
    minHeight: "full",
    align: "center",
  },
  text: {
    overline: "",
    title: "",
    body: "",
    align: "left",
  },
  presentation: {
    overline: "Vocación",
    title: "¿Por qué estudiar en el SEM?",
    subtitle: "",
    description: "",
    highlights: [],
    showVerse: false,
    verseText: "",
    verseReference: "",
  },
  feature_grid: {
    overline: "Vocación",
    title: "¿Por qué estudiar en el SEM?",
    description:
      "Formación integral para quienes responden al llamado al ministerio ordenado, con acompañamiento académico y espiritual de excelencia.",
    features: [
      {
        id: "fg1",
        icon: "BookOpen",
        title: "Formación Bíblica",
        description: "Estudio profundo de las Escrituras como fundamento del ministerio.",
        order: 0,
        visible: true,
      },
      {
        id: "fg2",
        icon: "GraduationCap",
        title: "Excelencia Académica",
        description: "Programas rigurosos con docentes de trayectoria ministerial.",
        order: 1,
        visible: true,
      },
      {
        id: "fg3",
        icon: "Monitor",
        title: "Modalidad 100% Online",
        description: "Estudia desde cualquier lugar sin sacrificar calidad formativa.",
        order: 2,
        visible: true,
      },
      {
        id: "fg4",
        icon: "Heart",
        title: "Comunidad Nacional",
        description: "Red de seminaristas y egresados en todo Chile.",
        order: 3,
        visible: true,
      },
    ],
    emptyTitle: "",
    emptyDescription: "",
  },
  audience_profiles: {
    overline: "Perfil del postulante",
    title: "¿Este seminario es para ti?",
    description:
      "Si te reconoces en alguno de estos caminos, la formación del SEM puede ser tu próximo paso ministerial.",
    image: "",
    imageMediaId: "",
    imageAlt: "Estudiantes del SEM en formación bíblica",
    quote: "El SEM forma siervos para la Iglesia, no solo estudiantes.",
    ctaLabel: "Explorar admisión",
    ctaHref: "/admision",
    profiles: [],
  },
  modality: {
    overline: "Modalidad",
    title: "Estudia con flexibilidad",
    subtitle: "",
    description: "",
    image: "",
    imageMediaId: "",
    items: [],
    buttonLabel: "",
    buttonHref: "",
  },
  programs: {
    overline: "Académico",
    title: "Nuestros programas",
    description: "",
    showButton: true,
    buttonLabel: "Ver todos los programas",
    buttonHref: "/programas",
    query: blockTypeToDefaultQuery("programs"),
    emptyTitle: "Programas en actualización",
    emptyDescription: "Pronto publicaremos nuestro catálogo académico desde el CMS.",
    emptyActionLabel: "Ver programas",
    emptyActionHref: "/programas",
    errorTitle: "No fue posible cargar los programas",
    errorDescription: "Ocurrió un error al consultar el catálogo académico. Intenta de nuevo más tarde.",
  },
  academic_offer: {
    overline: "Programas formativos",
    title: "Nuestros programas",
    description:
      "Formación bíblica y pastoral 100% online, diseñada para equiparte y fortalecer tu llamado ministerial.",
    showButton: true,
    buttonLabel: "Ver todos los programas",
    buttonHref: "/programas",
    cardCtaLabel: "Conocer programa",
    pageSize: 3,
    showPagination: true,
    showHelpCta: true,
    helpTitle: "¿No sabes qué programa es para ti?",
    helpDescription: "Nuestro equipo de admisiones puede orientarte en tu proceso.",
    helpPrimaryLabel: "Hablar con admisiones",
    helpPrimaryHref: "/contacto",
    helpSecondaryLabel: "Ver guía de programas",
    helpSecondaryHref: "/admision",
    showAudienceSection: false,
    query: blockTypeToDefaultQuery("academic_offer"),
    emptyTitle: "Programas en actualización",
    emptyDescription: "Pronto publicaremos nuestro catálogo académico desde el CMS.",
    emptyActionLabel: "Ver programas",
    emptyActionHref: "/programas",
    errorTitle: "No fue posible cargar los programas",
    errorDescription: "Ocurrió un error al consultar el catálogo académico. Intenta de nuevo más tarde.",
  },
  seminarios_home: {
    eyebrow: "Formación continua",
    title: "Seminarios formativos",
    description:
      "Programas formativos cortos y especializados para profundizar en áreas clave del ministerio. Modalidad online con certificación SEM.",
    viewAllHref: "/programas",
    viewAllLabel: "Ver todos los programas formativos",
  },
  teachers: {
    overline: "Equipo",
    title: "Nuestros formadores",
    description: "",
    showButton: true,
    buttonLabel: "Ver equipo completo",
    buttonHref: "/equipo",
    cardCtaLabel: "Conocer más",
    query: blockTypeToDefaultQuery("teachers"),
    emptyTitle: "Equipo en actualización",
    emptyDescription: "Los perfiles del equipo institucional se publicarán desde el CMS.",
    emptyActionLabel: "Conocer al equipo",
    emptyActionHref: "/equipo",
    errorTitle: "No fue posible cargar el equipo",
    errorDescription: "Ocurrió un error al consultar los perfiles. Intenta de nuevo más tarde.",
  },
  people: {
    overline: "Docencia",
    title: "Equipo docente",
    description: "Docentes con trayectoria académica y pastoral al servicio de la Iglesia.",
    showButton: true,
    buttonLabel: "Conocer al equipo",
    buttonHref: "/equipo",
    cardCtaLabel: "Ver perfil",
    query: blockTypeToDefaultQuery("people"),
    emptyTitle: "Equipo en actualización",
    emptyDescription: "Los perfiles se publicarán desde el CMS.",
    emptyActionLabel: "Conocer al equipo",
    emptyActionHref: "/equipo",
    errorTitle: "No fue posible cargar las personas",
    errorDescription: "Ocurrió un error al consultar los perfiles. Intenta de nuevo más tarde.",
  },
  news: {
    overline: "Actualidad institucional",
    title: "Noticias y vida seminarista",
    description: "Novedades, eventos y comunicados de nuestra comunidad de formación.",
    showButton: true,
    buttonLabel: "Ver todas las noticias",
    buttonHref: "/noticias",
    query: blockTypeToDefaultQuery("news"),
    emptyTitle: "Sin noticias publicadas",
    emptyDescription: "Las novedades aparecerán aquí cuando se publiquen desde el CMS.",
    emptyActionLabel: "Ver noticias",
    emptyActionHref: "/noticias",
    errorTitle: "No fue posible cargar las noticias",
    errorDescription: "Intenta de nuevo más tarde.",
    readMoreLabel: "Leer más",
    cardCtaLabel: "Leer más",
  },
  events: {
    overline: "Agenda",
    title: "Próximos eventos",
    description: "Actividades, conferencias y celebraciones de nuestra comunidad.",
    showButton: true,
    buttonLabel: "Ver agenda completa",
    buttonHref: "/eventos",
    query: blockTypeToDefaultQuery("events"),
    emptyTitle: "Sin eventos programados",
    emptyDescription: "La agenda institucional se actualizará próximamente.",
    emptyActionLabel: "Ver eventos",
    emptyActionHref: "/eventos",
    errorTitle: "No fue posible cargar los eventos",
    errorDescription: "Intenta de nuevo más tarde.",
    viewEventLabel: "Ver evento",
  },
  academic_agenda: {
    overline: "Calendario",
    title: "Agenda académica",
    description: "Hitos oficiales del año formativo del seminario.",
    showButton: true,
    buttonLabel: "Ver calendario completo",
    buttonHref: "/agenda-academica",
    query: blockTypeToDefaultQuery("academic_agenda"),
    emptyTitle: "Sin hitos programados",
    emptyDescription: "El calendario académico se publicará desde el CMS.",
    emptyActionLabel: "Ver agenda",
    emptyActionHref: "/agenda-academica",
    errorTitle: "No fue posible cargar la agenda",
    errorDescription: "Intenta de nuevo más tarde.",
    viewEventLabel: "Ver detalle",
  },
  institutional_notices: {
    overline: "Comunicados",
    title: "Avisos institucionales",
    description: "Información oficial de la Dirección del Seminario.",
    showButton: true,
    buttonLabel: "Ver todos los avisos",
    buttonHref: "/avisos",
    query: blockTypeToDefaultQuery("institutional_notices"),
    emptyTitle: "Sin avisos publicados",
    emptyDescription: "Los comunicados oficiales aparecerán aquí.",
    emptyActionLabel: "Ver avisos",
    emptyActionHref: "/avisos",
    errorTitle: "No fue posible cargar los avisos",
    errorDescription: "Intenta de nuevo más tarde.",
    readMoreLabel: "Leer aviso",
  },
  library: {
    overline: "Biblioteca institucional",
    title: "Material formativo para tu camino",
    description: "Recursos académicos y espirituales que complementan tu formación bíblica y ministerial.",
    showButton: true,
    buttonLabel: "Consultar biblioteca",
    buttonHref: "/biblioteca",
    query: blockTypeToDefaultQuery("library"),
    emptyTitle: "Biblioteca en preparación",
    emptyDescription: "El material formativo institucional estará disponible próximamente.",
    emptyActionLabel: "Consultar biblioteca",
    emptyActionHref: "/biblioteca",
    errorTitle: "No fue posible cargar la biblioteca",
    errorDescription: "Intenta de nuevo más tarde.",
    cardCtaLabel: "Consultar recurso",
  },
  resources: {
    overline: "Destacados",
    title: "Material formativo recomendado",
    description: "Material formativo seleccionado para la comunidad seminarista del SEM.",
    items: [],
  },
  cta: {
    title: "¿Listo para dar el siguiente paso?",
    description: "Inicia tu proceso de postulación o conversa con un asesor del seminario.",
    primaryLabel: "Postular ahora",
    primaryHref: "/admision",
    secondaryLabel: "Hablar con un asesor",
    secondaryHref: "/contacto",
    variant: "primary",
  },
  cta_premium: {
    overline: "Tu próximo paso",
    title: "¿Listo para transformar tu ministerio?",
    description:
      "Únete a una comunidad de formación seria, flexible y profundamente arraigada en la fe. Postula hoy o solicita orientación personalizada.",
    variant: "highlight",
    background: "primary",
    image: "/images/hero-institutional.svg",
    imageAlt: "Comunidad seminarista del SEM",
    showStats: true,
    stats: [
      { id: "1", value: "+150", label: "estudiantes", visible: true },
      { id: "2", value: "25", label: "años formando líderes", visible: true },
      { id: "3", value: "100%", label: "modalidad online", visible: true },
      { id: "4", value: "Docentes", label: "con experiencia ministerial", visible: true },
    ],
    buttons: [
      {
        id: "1",
        label: "Postular ahora",
        action: { type: "url", href: "/admision" },
        variant: "primary",
        visible: true,
      },
      {
        id: "2",
        label: "Solicitar información",
        action: { type: "form", formId: "contact" },
        variant: "outline",
        visible: true,
      },
    ],
  },
  admission_process: {
    overline: "Admisión",
    title: "Comienza tu proceso",
    description: "Cuatro pasos claros desde el descubrimiento hasta la matrícula.",
    items: [
      { id: "1", step: 1, title: "Explora el programa", description: "Conoce nuestros programas formativos y el perfil del seminarista." },
      { id: "2", step: 2, title: "Revisa requisitos", description: "Verifica los requisitos académicos, pastorales y documentales." },
      { id: "3", step: 3, title: "Completa la postulación", description: "Envía tu solicitud en línea con la documentación requerida." },
      { id: "4", step: 4, title: "Formaliza matrícula", description: "Recibe acompañamiento para completar tu ingreso al seminario." },
    ],
  },
  timeline: {
    overline: "Formación",
    title: "Ruta Formativa",
    description: "Un camino estructurado desde la vocación hasta el servicio ministerial.",
    layout: "auto",
    variant: "process",
    items: [
      {
        id: "route-1",
        step: 1,
        title: "Vocación",
        description: "Discernimiento del llamado y acompañamiento espiritual inicial.",
        icon: "Heart",
        order: 0,
        status: "completed",
        visible: true,
      },
      {
        id: "route-2",
        step: 2,
        title: "Formación Bíblica",
        description: "Base sólida en las Escrituras, teología y tradición de la Iglesia.",
        icon: "BookOpen",
        order: 1,
        status: "active",
        visible: true,
      },
      {
        id: "route-3",
        step: 3,
        title: "Práctica Ministerial",
        description: "Experiencia pastoral supervisada y desarrollo de habilidades de servicio.",
        icon: "Users",
        order: 2,
        status: "upcoming",
        visible: true,
      },
      {
        id: "route-4",
        step: 4,
        title: "Servicio Cristiano",
        description: "Preparación para el ministerio ordenado y la misión evangelizadora.",
        icon: "GraduationCap",
        order: 3,
        status: "upcoming",
        visible: true,
      },
    ],
    emptyTitle: "Ruta en actualización",
    emptyDescription: "Las etapas formativas se configurarán desde el CMS.",
  },
  scholarships: {
    overline: "Apoyo",
    title: "Becas y beneficios",
    description: "Opciones de financiamiento y convenios para tu formación.",
    items: [
      { id: "s1", kind: "scholarship", title: "Becas de mérito", description: "Apoyo parcial para estudiantes destacados." },
      { id: "s2", kind: "discount", title: "Descuentos pastorales", description: "Beneficios para ministros y líderes de iglesia." },
      { id: "s3", kind: "agreement", title: "Convenios institucionales", description: "Acuerdos con diócesis y organizaciones aliadas." },
      { id: "s4", kind: "benefit", title: "Beneficios estudiantiles", description: "Acceso a biblioteca digital y recursos formativos." },
    ],
  },
  faq: {
    overline: "Ayuda",
    title: "Preguntas frecuentes",
    description: "Respuestas a las dudas más comunes sobre admisión y formación.",
    items: [
      { id: "f1", question: "¿Quién puede postular?", answer: "Personas con vocación al ministerio ordenado que cumplan los requisitos académicos y pastorales." },
      { id: "f2", question: "¿La modalidad es 100% online?", answer: "Sí, ofrecemos formación en línea con acompañamiento académico y espiritual continuo." },
      { id: "f3", question: "¿Cuánto dura el proceso de admisión?", answer: "El proceso típico toma entre 2 y 4 semanas según la documentación entregada." },
    ],
  },
  quick_contact: {
    overline: "Contacto",
    title: "¿Tienes dudas? Escríbenos",
    description: "Nuestro equipo de admisiones está disponible para orientarte.",
    showWhatsapp: true,
    showEmail: true,
    showPhone: true,
    showHours: true,
    showAddress: true,
  },
  contact_hub: {
    overline: "Contacto",
    title: "¿Cómo podemos acompañarte?",
    description: "Escríbenos o visítanos. Nuestro equipo de admisiones orienta tu proceso de postulación.",
    showMap: true,
    showHours: true,
    showSocial: true,
    showLocations: false,
    showForm: true,
    mapProvider: "google",
    formId: "contact",
    useInstitutionDefaults: true,
    channels: [],
    locations: [],
    actions: [],
  },
  experience_form: {
    formId: "information-request",
    overline: "Formulario",
    title: "",
    description: "",
    display: "inline",
  },
  footer_premium: {
    showDescription: true,
    showNavigation: true,
    showContact: true,
    showSocial: true,
    showLegal: true,
  },
  alliance: {
    title: "",
    description: "",
  },
  testimonials: {
    overline: "Testimonios",
    title: "Voces de nuestra comunidad",
    description: "",
    query: blockTypeToDefaultQuery("testimonials"),
    errorTitle: "No fue posible cargar los testimonios",
    errorDescription: "Intenta de nuevo más tarde.",
  },
  gallery: {
    overline: "Campus",
    title: "Vida en el seminario",
    description: "",
    showButton: false,
    buttonLabel: "",
    buttonHref: "",
    query: blockTypeToDefaultQuery("gallery"),
    emptyTitle: "Galería en preparación",
    emptyDescription: "Las fotografías se publicarán desde la Media Library.",
    errorTitle: "No fue posible cargar la galería",
    errorDescription: "Intenta de nuevo más tarde.",
  },
  stats: {
    overline: "",
    title: "",
    items: [],
  },
  video: {
    title: "",
    description: "",
    videoUrl: "",
    poster: "",
  },
  verse: {
    text: "",
    reference: "",
    background: "gradient",
    image: "",
    imageMediaId: "",
  },
  contact: {
    title: "Contáctanos",
    description: "",
    showPhone: true,
    showEmail: true,
    showAddress: true,
  },
  divider: {
    variant: "default",
    spacing: "md",
  },
  html: {
    content: "",
  },
  markdown: {
    content: "",
  },
};

export function createDefaultBlock(type: BlockType, order: number): PageBlock {
  return {
    id: createBlockId(type),
    type,
    visible: true,
    order,
    settings: { ...DEFAULT_SETTINGS[type] },
  };
}

export const DEFAULT_TEMPLATES: CmsTemplate[] = [
  {
    _id: "home",
    name: "Home Institucional",
    description: "Plantilla principal del portal",
    template: "institutional",
    enabled: true,
    blocks: [
      { type: "hero" },
      { type: "academic_offer" },
      { type: "audience_profiles" },
      { type: "modality" },
      { type: "people" },
      { type: "testimonials" },
      { type: "admission_process" },
      { type: "faq" },
      { type: "cta_premium" },
    ],
  },
  {
    _id: "landing",
    name: "Landing",
    description: "Página de conversión",
    template: "landing",
    enabled: true,
    blocks: [{ type: "hero" }, { type: "text" }, { type: "cta" }],
  },
  {
    _id: "contact",
    name: "Contacto",
    description: "Página de contacto",
    template: "contact",
    enabled: true,
    blocks: [{ type: "text" }, { type: "contact_hub" }],
  },
];

export function blocksFromTemplate(template: CmsTemplate): PageBlock[] {
  return template.blocks.map((entry, index) => {
    const block = createDefaultBlock(entry.type, index);
    if (entry.settings) {
      block.settings = { ...block.settings, ...entry.settings };
    }
    block.id = createBlockId(entry.type);
    return block;
  });
}

export const SEED_HOME_BLOCK_DATA = {
  hero: DEFAULT_SEM_PREMIUM_HERO,
  presentation: {
    overline: "Vocación",
    title: "¿Por qué estudiar en el SEM?",
    subtitle: "Una experiencia formativa que integra fe, razón y servicio pastoral.",
    description:
      "Formación integral para quienes responden al llamado al ministerio ordenado, con acompañamiento académico y espiritual de excelencia.",
    highlights: [
      {
        id: "h1",
        icon: "BookOpen",
        title: "Formación Bíblica",
        description: "Estudio profundo de la Sagrada Escritura como fundamento del ministerio.",
        order: 0,
        visible: true,
      },
      {
        id: "h2",
        icon: "GraduationCap",
        title: "Docentes con experiencia",
        description: "Docentes con trayectoria académica y pastoral al servicio de la Iglesia.",
        order: 1,
        visible: true,
      },
      {
        id: "h3",
        icon: "Calendar",
        title: "Modalidad flexible",
        description: "Esquemas de estudio adaptados a las necesidades de la comunidad seminarista.",
        order: 2,
        visible: true,
      },
      {
        id: "h4",
        icon: "Heart",
        title: "Comunidad nacional",
        description: "Red de seminaristas y egresados en todo el país.",
        order: 3,
        visible: true,
      },
    ],
  },
  feature_grid: {
    overline: "Vocación",
    title: "¿Por qué estudiar en el SEM?",
    description:
      "Formación integral para quienes responden al llamado al ministerio ordenado, con acompañamiento académico y espiritual de excelencia.",
    features: [
      {
        id: "f1",
        icon: "BookOpen",
        title: "Formación Bíblica",
        description: "Estudio profundo de la Sagrada Escritura como fundamento del ministerio.",
        order: 0,
        visible: true,
      },
      {
        id: "f2",
        icon: "GraduationCap",
        title: "Docentes con experiencia",
        description: "Docentes con trayectoria académica y pastoral al servicio de la Iglesia.",
        order: 1,
        visible: true,
      },
      {
        id: "f3",
        icon: "Calendar",
        title: "Modalidad flexible",
        description: "Esquemas de estudio adaptados a las necesidades de la comunidad seminarista.",
        order: 2,
        visible: true,
      },
      {
        id: "f4",
        icon: "Heart",
        title: "Comunidad nacional",
        description: "Red de seminaristas y egresados en todo el país.",
        order: 3,
        visible: true,
      },
    ],
  },
  modality: {
    overline: "Metodología",
    title: "Cómo se estudia en el SEM",
    subtitle: "Formación accesible sin sacrificar rigor académico.",
    description:
      "Combinamos clases en línea, campus virtual y acompañamiento pastoral para una experiencia formativa completa.",
    items: [
      {
        id: "m1",
        icon: "Calendar",
        title: "Clases en vivo",
        description: "Sesiones sincrónicas y material formativo disponible en el campus virtual.",
      },
      {
        id: "m2",
        icon: "BookOpen",
        title: "Campus virtual",
        description: "Material formativo, recursos y seguimiento académico en un solo lugar.",
      },
      {
        id: "m3",
        icon: "Heart",
        title: "Acompañamiento",
        description: "Formadores y mentores disponibles durante tu camino formativo.",
      },
      {
        id: "m4",
        icon: "GraduationCap",
        title: "Flexibilidad",
        description: "Ritmos de estudio adaptados a tu contexto ministerial.",
      },
      {
        id: "m5",
        icon: "Library",
        title: "Comunidad",
        description: "Vínculos con seminaristas de distintas diócesis y regiones.",
      },
    ],
  },
  stats: {
    overline: "Trayectoria",
    title: "Números que respaldan nuestra misión",
    items: [
      { id: "1", value: "+40", label: "Años de historia" },
      { id: "2", value: "+500", label: "Egresados" },
      { id: "3", value: "100%", label: "Online" },
      { id: "4", value: "Nacional", label: "Cobertura" },
    ],
  },
  verse: {
    text: "Equipando a los santos para la obra del ministerio.",
    reference: "Efesios 4:12",
    background: "gradient",
  },
  gallery: {
    overline: "Campus",
    title: "Vida estudiantil",
    description: "Momentos de formación, comunidad y vida espiritual en el seminario.",
    showButton: true,
    buttonLabel: "Conoce el campus",
    buttonHref: "/institucion",
  },
  news: {
    overline: "Actualidad institucional",
    title: "Noticias y vida seminarista",
    description: "Novedades, eventos y comunicados de nuestra comunidad de formación.",
  },
  events: {
    overline: "Agenda",
    title: "Próximos eventos",
    description: "Actividades, conferencias y celebraciones de nuestra comunidad.",
  },
  library: {
    overline: "Biblioteca institucional",
    title: "Material formativo para tu camino",
    description: "Recursos académicos y espirituales que complementan tu formación bíblica y ministerial.",
  },
  resources: {
    overline: "Destacados",
    title: "Material formativo recomendado",
    description: "Material formativo seleccionado para la comunidad seminarista del SEM.",
    items: [
      {
        id: "r1",
        resourceType: "Clase abierta",
        icon: "GraduationCap",
        title: "Introducción a la Teología Pastoral",
        description: "Sesión gratuita para conocer nuestro enfoque formativo.",
        href: "/programas/diploma-teologia-biblica-pastoral-g2023",
        ctaLabel: "Ver clase",
      },
      {
        id: "r2",
        resourceType: "Devocional",
        icon: "BookOpen",
        title: "Devocional de la semana",
        description: "Reflexión semanal para acompañar tu vida espiritual.",
        href: "/biblioteca",
        ctaLabel: "Leer devocional",
      },
      {
        id: "r3",
        resourceType: "Video",
        icon: "Calendar",
        title: "Vida en el seminario",
        description: "Conoce la experiencia de formación en el SEM.",
        href: "/institucion",
        ctaLabel: "Ver video",
      },
    ],
  },
  cta: {
    title: "¿Listo para dar el siguiente paso?",
    description: "Inicia tu proceso de postulación o conversa con un asesor del seminario.",
    primaryLabel: "Postular ahora",
    primaryHref: "/admision",
    secondaryLabel: "Hablar con un asesor",
    secondaryHref: "/contacto",
  },
  admission_process: {
    overline: "Admisión",
    title: "Comienza tu proceso",
    description: "Cuatro pasos claros desde el descubrimiento hasta la matrícula.",
  },
  timeline: {
    overline: "Formación",
    title: "Ruta Formativa",
    description: "Un camino estructurado desde la vocación hasta el servicio ministerial.",
  },
  people: {
    overline: "Docencia",
    title: "Equipo docente",
    description: "Docentes con trayectoria académica y pastoral al servicio de la Iglesia.",
  },
  cta_premium: {
    overline: "Tu próximo paso",
    title: "¿Listo para transformar tu ministerio?",
    description:
      "Únete a una comunidad de formación seria, flexible y profundamente arraigada en la fe.",
    image: "/images/hero-institutional.svg",
  },
  scholarships: {
    overline: "Apoyo",
    title: "Becas y beneficios",
    description: "Opciones de financiamiento y convenios para tu formación.",
  },
  faq: {
    overline: "Ayuda",
    title: "Preguntas frecuentes",
    description: "Respuestas a las dudas más comunes sobre admisión y formación.",
  },
  quick_contact: {
    overline: "Contacto",
    title: "¿Tienes dudas? Escríbenos",
    description: "Nuestro equipo de admisiones está disponible para orientarte.",
  },
};
